name: genus_gems
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  html: ^0.15.6
  cached_network_image: ^3.4.1
  http: ^1.6.0
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  auto_size_text: ^3.0.0
  dio: ^5.9.2
  flutter_riverpod: ^3.3.1
  connectivity_plus: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/icons/social/
    - assets/images/
    - assets/lottie/
    - assets/animations/
    - assets/videos/
    - assets/fonts/NotoSans-Regular.ttf

